### ISSUE TITLE
How change ocr language?

### ISSUE THREAD

**Issue by Radzhab** [YaoXuanZhi/OneNoteOCR#1]
Subj

**Comment by YaoXuanZhi** [comment]
I suggest you visit this [website](https://answers.microsoft.com/zh-hans/office/forum/office_2010-onenote/office-2010-onenote/13ca0c5c-fbc4-48a3-94c9-aa37a5746652?msgId=a62e9ca0-0368-4c99-a5b0-ecfaa3ebbf41).Briefly,it is a good practice that downloading a language-package which you needed.

**Comment by YaoXuanZhi** [comment]
In addition,you maybe change default language on OneNote product O(∩_∩)O~
